import Link from "next/link";
import { prisma } from "../lib/prisma";
import { checkAndRunIngestionIfNeeded } from "../services/ingestRunner";
import {
  ArrowRight,
  Cpu,
  Sparkles,
  Zap,
  Globe,
  Shield,
  BarChart3,
  Rss,
  Clock,
  Layers,
  TrendingUp,
  BrainCircuit,
  CheckCircle2,
  BookOpen,
  Bell,
} from "lucide-react";

export const dynamic = "force-dynamic";

export default async function HomePage() {
  await checkAndRunIngestionIfNeeded();

  const [
    totalArticles,
    totalSources,
    latestArticles,
    startupArticles,
    totalCategories,
  ] = await Promise.all([
    prisma.article.count({ where: { status: { not: "failed" } } }),
    prisma.source.count({ where: { active: true } }),
    prisma.article.findMany({
      where: { status: { not: "failed" } },
      orderBy: { publishedAt: "desc" },
      take: 5,
      include: { category: { select: { name: true, slug: true } } },
    }),
    prisma.article.findMany({
      where: { status: { not: "failed" }, category: { slug: "startups" } },
      orderBy: { publishedAt: "desc" },
      take: 3,
      include: { category: { select: { name: true, slug: true } } },
    }),
    prisma.category.count(),
  ]);

  const sources = [
    "OpenAI", "Google DeepMind", "Anthropic", "Hugging Face",
    "TechCrunch", "MIT Technology Review", "arXiv", "The Verge",
    "Wired", "VentureBeat", "IEEE Spectrum", "Nature AI",
  ];

  const features = [
    {
      icon: BrainCircuit,
      color: "from-indigo-500 to-violet-600",
      bg: "bg-indigo-500/10",
      border: "border-indigo-500/20",
      iconColor: "text-indigo-400",
      title: "Gemini AI Summaries",
      desc: "Every article gets a rich 10-line summary generated by Google Gemini — you get the insight without reading the full piece.",
    },
    {
      icon: Rss,
      color: "from-emerald-500 to-teal-600",
      bg: "bg-emerald-500/10",
      border: "border-emerald-500/20",
      iconColor: "text-emerald-400",
      title: "Live RSS Aggregation",
      desc: "We monitor 20+ trusted AI and tech RSS feeds continuously — articles arrive within minutes of publication.",
    },
    {
      icon: Globe,
      color: "from-blue-500 to-cyan-600",
      bg: "bg-blue-500/10",
      border: "border-blue-500/20",
      iconColor: "text-blue-400",
      title: "Multi-Source Coverage",
      desc: "From OpenAI to Google DeepMind, arXiv to TechCrunch — all the key voices in one curated, deduplicated stream.",
    },
    {
      icon: Bell,
      color: "from-amber-500 to-orange-600",
      bg: "bg-amber-500/10",
      border: "border-amber-500/20",
      iconColor: "text-amber-400",
      title: "Smart Bookmarking",
      desc: "Save articles to your Personal Vault and revisit any AI summary. Build your own research library effortlessly.",
    },
    {
      icon: BookOpen,
      color: "from-purple-500 to-pink-600",
      bg: "bg-purple-500/10",
      border: "border-purple-500/20",
      iconColor: "text-purple-400",
      title: "AI Chat Assistant",
      desc: "Ask follow-up questions about any article. Our Gemini-powered assistant explains, expands, and analyzes on demand.",
    },
    {
      icon: Shield,
      color: "from-rose-500 to-red-600",
      bg: "bg-rose-500/10",
      border: "border-rose-500/20",
      iconColor: "text-rose-400",
      title: "Zero Noise Policy",
      desc: "Strict deduplication removes reposts and low-quality content. Every item in your feed earns its place.",
    },
  ];

  const categories = [
    { name: "AI Research", slug: "artificial-intelligence", icon: Cpu, color: "text-indigo-400 bg-indigo-500/10 border-indigo-500/20" },
    { name: "Machine Learning", slug: "machine-learning", icon: Zap, color: "text-blue-400 bg-blue-500/10 border-blue-500/20" },
    { name: "Generative AI", slug: "generative-ai", icon: Sparkles, color: "text-purple-400 bg-purple-500/10 border-purple-500/20" },
    { name: "Cloud Computing", slug: "cloud-computing", icon: Globe, color: "text-cyan-400 bg-cyan-500/10 border-cyan-500/20" },
    { name: "Cybersecurity", slug: "cybersecurity", icon: Shield, color: "text-rose-400 bg-rose-500/10 border-rose-500/20" },
    { name: "Dev Tools", slug: "developer-tools", icon: Layers, color: "text-emerald-400 bg-emerald-500/10 border-emerald-500/20" },
    { name: "Startups", slug: "startups", icon: TrendingUp, color: "text-amber-400 bg-amber-500/10 border-amber-500/20" },
    { name: "Data Science", slug: "data-science", icon: BarChart3, color: "text-teal-400 bg-teal-500/10 border-teal-500/20" },
  ];

  return (
    <div className="relative overflow-x-hidden min-h-screen bg-background text-foreground">

      {/* ── GLOBAL ANIMATION STYLES ── */}
      <style dangerouslySetInnerHTML={{ __html: `
        @keyframes grid-move {
          0% { background-position: 0 0; }
          100% { background-position: 0 80px; }
        }
        .perspective-container { perspective: 300px; perspective-origin: 50% 30%; }
        .grid-mesh {
          width: 300%; height: 180%; top: -20%; left: -100%;
          background-image:
            linear-gradient(rgba(99,102,241,0.05) 1px, transparent 1px),
            linear-gradient(90deg, rgba(99,102,241,0.05) 1px, transparent 1px);
          background-size: 40px 40px;
          transform: rotateX(65deg);
          animation: grid-move 16s linear infinite;
        }
        @keyframes float-up {
          0%   { transform: translateY(0) translateX(0) scale(0.9); opacity: 0; }
          10%  { opacity: 0.5; }
          90%  { opacity: 0.5; }
          100% { transform: translateY(-320px) translateX(20px) scale(1.1); opacity: 0; }
        }
        .p1 { animation: float-up 10s linear infinite; }
        .p2 { animation: float-up 13s linear infinite 3s; }
        .p3 { animation: float-up 11s linear infinite 5.5s; }
        .p4 { animation: float-up 15s linear infinite 8s; }
        .p5 { animation: float-up 9s linear infinite 1.5s; }
        @keyframes pulse-slow {
          0%,100% { opacity: 0.5; transform: scale(1); }
          50% { opacity: 1; transform: scale(1.05); }
        }
        .orb { animation: pulse-slow 8s ease-in-out infinite; }
        @keyframes ticker {
          0% { transform: translateX(0); }
          100% { transform: translateX(-50%); }
        }
        .ticker-track { animation: ticker 30s linear infinite; }
        .ticker-track:hover { animation-play-state: paused; }
        @keyframes slide-up {
          from { opacity: 0; transform: translateY(30px); }
          to { opacity: 1; transform: translateY(0); }
        }
        .anim-1 { animation: slide-up 0.7s cubic-bezier(.16,1,.3,1) both; }
        .anim-2 { animation: slide-up 0.7s cubic-bezier(.16,1,.3,1) 0.1s both; }
        .anim-3 { animation: slide-up 0.7s cubic-bezier(.16,1,.3,1) 0.2s both; }
        .anim-4 { animation: slide-up 0.7s cubic-bezier(.16,1,.3,1) 0.3s both; }
        @keyframes count-up { from { opacity: 0; } to { opacity: 1; } }
      `}} />

      {/* ══════════════════════════════════ HERO ══════════════════════════════════ */}
      <section className="relative min-h-[90vh] flex flex-col items-center justify-center text-center px-4 overflow-hidden pt-20 pb-16">

        {/* — Background Layers — */}
        <div className="absolute inset-0 pointer-events-none z-0 overflow-hidden select-none">
          {/* Dark radial vignette */}
          <div className="absolute inset-0 bg-[radial-gradient(ellipse_80%_60%_at_50%_40%,transparent_30%,var(--background)_100%)] z-10" />

          {/* Perspective grid */}
          <div className="perspective-container absolute inset-0 w-full h-full">
            <div className="grid-mesh absolute" />
          </div>

          {/* Big glow orbs */}
          <div className="orb absolute top-1/3 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[500px] h-[500px] rounded-full bg-indigo-600/10 blur-[140px]" />
          <div className="orb absolute top-1/2 left-[30%] w-[300px] h-[300px] rounded-full bg-purple-600/8 blur-[100px]" style={{ animationDelay: "2s" }} />
          <div className="orb absolute top-1/3 left-[65%] w-[250px] h-[250px] rounded-full bg-violet-500/6 blur-[90px]" style={{ animationDelay: "4s" }} />

          {/* Floating particles */}
          <span className="p1 absolute w-2 h-2 rounded-full bg-indigo-400/70 left-[15%] bottom-[10%]" />
          <span className="p2 absolute w-1.5 h-1.5 rounded-full bg-purple-400/60 left-[45%] bottom-[20%]" />
          <span className="p3 absolute w-2 h-2 rounded-full bg-pink-400/50 left-[75%] bottom-[5%]" />
          <span className="p4 absolute w-1 h-1 rounded-full bg-indigo-300/60 left-[60%] bottom-[35%]" />
          <span className="p5 absolute w-1.5 h-1.5 rounded-full bg-violet-400/50 left-[28%] bottom-[25%]" />
        </div>

        {/* — Content — */}
        <div className="relative z-10 max-w-4xl mx-auto space-y-8">

          {/* Live Status Badge */}
          <div className="anim-1 flex justify-center">
            <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full border border-emerald-500/25 bg-emerald-500/8 text-xs font-bold text-emerald-400 shadow-sm backdrop-blur-sm select-none">
              <span className="relative flex h-2 w-2">
                <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-emerald-400 opacity-75" />
                <span className="relative inline-flex rounded-full h-2 w-2 bg-emerald-500" />
              </span>
              LIVE &nbsp;·&nbsp; {totalArticles.toLocaleString()} articles indexed &nbsp;·&nbsp;
              <Clock className="h-3 w-3" /> updated hourly
            </div>
          </div>

          {/* Headline */}
          <div className="anim-2 space-y-4">
            <h1 className="text-5xl sm:text-6xl lg:text-7xl xl:text-8xl font-black tracking-tighter leading-[0.95] text-foreground">
              The AI news
              <br />
              <span className="bg-gradient-to-r from-indigo-400 via-violet-400 to-purple-500 bg-clip-text text-transparent">
                that actually matters.
              </span>
            </h1>
            <p className="text-base sm:text-lg text-muted-foreground leading-relaxed max-w-xl mx-auto">
              {totalSources} trusted RSS sources. Deduplicated, summarized by{" "}
              <span className="text-foreground font-semibold">Gemini AI</span>, and delivered in clean signal — zero noise.
            </p>
          </div>

          {/* CTAs */}
          <div className="anim-3 flex flex-wrap items-center justify-center gap-3">
            <Link
              href="/news"
              className="group inline-flex items-center gap-2 px-7 py-3.5 rounded-full font-bold text-sm text-white shadow-lg transition-all duration-300 hover:scale-105 hover:shadow-indigo-500/30"
              style={{ background: "linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%)", boxShadow: "0 4px 24px rgba(99,102,241,0.35)" }}
            >
              Browse Latest News
              <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1" />
            </Link>
            <Link
              href="/auth"
              className="inline-flex items-center gap-2 px-7 py-3.5 rounded-full border border-border bg-card/50 backdrop-blur-sm font-semibold text-sm hover:bg-card hover:border-indigo-500/40 transition-all duration-200"
            >
              <Sparkles className="h-4 w-4 text-indigo-400" />
              Get Free Access
            </Link>
          </div>

          {/* Trust indicators */}
          <div className="anim-4 flex flex-wrap items-center justify-center gap-x-6 gap-y-2 text-[11px] text-muted-foreground pt-2">
            {["No credit card required", "Hourly updates", "AI summaries on every article", "Free forever"].map((item) => (
              <span key={item} className="flex items-center gap-1.5">
                <CheckCircle2 className="h-3 w-3 text-emerald-500 shrink-0" />
                {item}
              </span>
            ))}
          </div>
        </div>
      </section>

      {/* ══════════════════ SCROLLING SOURCE TICKER ══════════════════ */}
      <section className="relative z-10 py-8 border-y border-border/30 overflow-hidden bg-background/50 backdrop-blur-sm">
        <p className="text-center text-[10px] uppercase tracking-widest font-bold text-muted-foreground mb-5">
          Aggregating from the world's top sources
        </p>
        <div className="overflow-hidden">
          <div className="ticker-track flex items-center gap-10 w-max px-6">
            {[...sources, ...sources].map((src, i) => (
              <span
                key={i}
                className="text-xs font-bold text-muted-foreground/60 hover:text-muted-foreground transition whitespace-nowrap uppercase tracking-widest"
              >
                {src}
              </span>
            ))}
          </div>
        </div>
      </section>

      {/* ══════════════════ STAT COUNTERS ══════════════════ */}
      <section className="relative z-10 max-w-5xl mx-auto px-4 py-16">
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          {[
            { value: totalArticles.toLocaleString(), label: "Articles Indexed", icon: BookOpen, color: "text-indigo-400", glow: "from-indigo-500/20 to-transparent" },
            { value: `${totalSources}+`, label: "Live RSS Sources", icon: Rss, color: "text-emerald-400", glow: "from-emerald-500/20 to-transparent" },
            { value: `${totalCategories}`, label: "Topic Categories", icon: Layers, color: "text-purple-400", glow: "from-purple-500/20 to-transparent" },
            { value: "1hr", label: "Refresh Interval", icon: Clock, color: "text-amber-400", glow: "from-amber-500/20 to-transparent" },
          ].map(({ value, label, icon: Icon, color, glow }) => (
            <div
              key={label}
              className="relative rounded-2xl border border-border bg-card/50 backdrop-blur-sm p-6 text-center overflow-hidden hover-card-bounce"
            >
              <div className={`absolute inset-0 bg-gradient-to-br ${glow} pointer-events-none`} />
              <div className="relative">
                <Icon className={`h-5 w-5 mx-auto mb-3 ${color}`} />
                <div className={`text-3xl sm:text-4xl font-black tracking-tight ${color}`}>{value}</div>
                <div className="text-[11px] text-muted-foreground font-semibold uppercase tracking-wide mt-1.5">{label}</div>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* ══════════════════ FEATURES GRID ══════════════════ */}
      <section className="relative z-10 max-w-6xl mx-auto px-4 pb-20">
        <div className="text-center mb-12 space-y-3">
          <span className="badge badge-brand">
            <Sparkles className="h-3 w-3" />
            Platform Features
          </span>
          <h2 className="text-3xl sm:text-4xl font-extrabold tracking-tight">
            Everything you need to{" "}
            <span className="bg-gradient-to-r from-indigo-400 to-purple-500 bg-clip-text text-transparent">
              stay ahead
            </span>
          </h2>
          <p className="text-muted-foreground text-base max-w-xl mx-auto">
            AI News Hub is built for researchers, developers, and professionals who can't afford to miss what's happening in AI.
          </p>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5">
          {features.map(({ icon: Icon, color, bg, border, iconColor, title, desc }) => (
            <div
              key={title}
              className={`group relative p-6 rounded-2xl border ${border} ${bg} hover-card-bounce overflow-hidden`}
            >
              {/* Glow accent */}
              <div className={`absolute top-0 right-0 w-24 h-24 rounded-full bg-gradient-to-br ${color} opacity-5 blur-2xl group-hover:opacity-10 transition-opacity duration-500`} />
              <div className="relative space-y-3">
                <div className={`inline-flex p-2.5 rounded-xl ${bg} border ${border}`}>
                  <Icon className={`h-5 w-5 ${iconColor}`} />
                </div>
                <h3 className="font-extrabold text-base text-foreground">{title}</h3>
                <p className="text-sm text-muted-foreground leading-relaxed">{desc}</p>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* ══════════════════ CATEGORIES PILLS ══════════════════ */}
      <section className="relative z-10 max-w-4xl mx-auto px-4 pb-16">
        <div className="text-center mb-8 space-y-2">
          <h2 className="text-2xl font-extrabold tracking-tight">Browse by Category</h2>
          <p className="text-sm text-muted-foreground">Dive deep into any corner of the AI ecosystem</p>
        </div>
        <div className="flex flex-wrap items-center justify-center gap-3">
          {categories.map((cat) => {
            const Icon = cat.icon;
            return (
              <Link
                key={cat.slug}
                href={`/news?category=${cat.slug}`}
                className={`flex items-center gap-2 px-4 py-2.5 rounded-full border text-sm font-semibold transition-all duration-200 hover:scale-105 hover:shadow-md ${cat.color}`}
              >
                <Icon className="h-4 w-4 shrink-0" />
                <span>{cat.name}</span>
              </Link>
            );
          })}
        </div>
      </section>

      {/* ══════════════════ LIVE FEED PREVIEW ══════════════════ */}
      <section className="relative z-10 max-w-5xl mx-auto px-4 pb-20">

        {/* Background glow */}
        <div className="absolute inset-0 bg-gradient-to-b from-indigo-500/[0.03] via-transparent to-transparent pointer-events-none rounded-3xl" />

        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-start">

          {/* LEFT: Latest Articles */}
          <div className="lg:col-span-7">
            <div className="rounded-2xl border border-border bg-card/50 backdrop-blur-sm overflow-hidden shadow-sm">
              {/* Header */}
              <div className="flex items-center justify-between px-6 py-4 border-b border-border/40">
                <h2 className="font-extrabold text-sm text-foreground flex items-center gap-2">
                  <span className="relative flex h-2 w-2">
                    <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-indigo-400 opacity-75" />
                    <span className="relative inline-flex rounded-full h-2 w-2 bg-indigo-500" />
                  </span>
                  Live Article Feed
                </h2>
                <Link
                  href="/news"
                  className="text-[10px] font-bold text-indigo-400 hover:text-indigo-300 transition flex items-center gap-1"
                >
                  View all <ArrowRight className="h-3 w-3" />
                </Link>
              </div>

              {/* Article rows */}
              <div className="divide-y divide-border/30">
                {latestArticles.length === 0 ? (
                  <div className="text-center py-10">
                    <Rss className="h-8 w-8 text-muted-foreground/30 mx-auto mb-2" />
                    <p className="text-xs text-muted-foreground">Feed ingestion running — articles arriving soon.</p>
                  </div>
                ) : (
                  latestArticles.map((art, i) => (
                    <Link
                      key={art.id}
                      href={`/news/${art.slug}`}
                      className="flex items-start gap-4 px-6 py-4 hover:bg-muted/30 transition-colors duration-150 group"
                    >
                      <span className="text-[10px] font-black text-muted-foreground/40 w-4 mt-0.5 shrink-0 tabular-nums">
                        {String(i + 1).padStart(2, "0")}
                      </span>
                      <div className="flex-1 min-w-0 space-y-1">
                        <div className="flex items-center gap-2">
                          {art.category && (
                            <span className="badge badge-brand text-[9px] py-0">
                              {art.category.name}
                            </span>
                          )}
                          <span className="text-[10px] text-muted-foreground">{art.sourceName}</span>
                        </div>
                        <p className="text-sm font-semibold text-foreground line-clamp-1 group-hover:text-indigo-400 transition-colors">
                          {art.title}
                        </p>
                        {art.summary && (
                          <p className="text-[11px] text-muted-foreground line-clamp-1 leading-relaxed">
                            {art.summary}
                          </p>
                        )}
                      </div>
                      <ArrowRight className="h-3.5 w-3.5 text-muted-foreground/40 group-hover:text-indigo-400 shrink-0 mt-1 transition-colors" />
                    </Link>
                  ))
                )}
              </div>

              {/* Footer CTA */}
              <div className="px-6 py-4 border-t border-border/40 bg-muted/20">
                <Link
                  href="/news"
                  className="group w-full flex items-center justify-center gap-2 py-2.5 rounded-xl border border-indigo-500/20 bg-indigo-500/8 text-indigo-400 text-xs font-bold hover:bg-indigo-500/15 transition-all duration-200"
                >
                  View All {totalArticles.toLocaleString()} Articles
                  <ArrowRight className="h-3.5 w-3.5 transition-transform group-hover:translate-x-0.5" />
                </Link>
              </div>
            </div>
          </div>

          {/* RIGHT: Stats + Startup Signals */}
          <div className="lg:col-span-5 space-y-5">

            {/* Stats card */}
            <div className="rounded-2xl border border-border bg-card/50 backdrop-blur-sm p-6 space-y-4 shadow-sm">
              <h3 className="font-extrabold text-sm text-foreground flex items-center gap-2">
                <BarChart3 className="h-4 w-4 text-pink-400" />
                Platform Pulse
              </h3>
              <div className="grid grid-cols-2 gap-3">
                <div className="p-4 rounded-xl bg-gradient-to-br from-indigo-500/10 to-transparent border border-indigo-500/15 text-left">
                  <span className="text-[10px] font-bold text-indigo-400/70 uppercase tracking-wider block mb-1">Articles</span>
                  <span className="text-3xl font-black text-indigo-400 tracking-tight">{totalArticles.toLocaleString()}</span>
                </div>
                <div className="p-4 rounded-xl bg-gradient-to-br from-emerald-500/10 to-transparent border border-emerald-500/15 text-left">
                  <span className="text-[10px] font-bold text-emerald-400/70 uppercase tracking-wider block mb-1">Sources</span>
                  <span className="text-3xl font-black text-emerald-400 tracking-tight">{totalSources}</span>
                </div>
                <div className="p-4 rounded-xl bg-gradient-to-br from-purple-500/10 to-transparent border border-purple-500/15 text-left">
                  <span className="text-[10px] font-bold text-purple-400/70 uppercase tracking-wider block mb-1">Categories</span>
                  <span className="text-3xl font-black text-purple-400 tracking-tight">{totalCategories}</span>
                </div>
                <div className="p-4 rounded-xl bg-gradient-to-br from-amber-500/10 to-transparent border border-amber-500/15 text-left">
                  <span className="text-[10px] font-bold text-amber-400/70 uppercase tracking-wider block mb-1">Refresh</span>
                  <span className="text-3xl font-black text-amber-400 tracking-tight">1hr</span>
                </div>
              </div>
            </div>

            {/* Startup Signals */}
            <div className="rounded-2xl border border-border bg-card/50 backdrop-blur-sm p-6 space-y-4 shadow-sm">
              <h3 className="font-extrabold text-sm text-foreground flex items-center gap-2">
                <TrendingUp className="h-4 w-4 text-yellow-400" />
                Startup Signals
              </h3>
              <div className="space-y-3">
                {startupArticles.length === 0 ? (
                  <div className="text-center py-4">
                    <TrendingUp className="h-7 w-7 text-muted-foreground/20 mx-auto mb-2" />
                    <p className="text-[11px] text-muted-foreground">Startup articles arriving soon.</p>
                  </div>
                ) : (
                  startupArticles.map((art) => (
                    <Link
                      key={art.id}
                      href={`/news/${art.slug}`}
                      className="group flex gap-3 text-xs leading-relaxed hover:bg-muted/30 rounded-xl p-2 -mx-2 transition-colors duration-150"
                    >
                      <span className="w-1.5 h-1.5 rounded-full bg-yellow-400/70 shrink-0 mt-1.5" />
                      <div className="space-y-0.5 min-w-0">
                        <p className="font-semibold text-foreground line-clamp-2 group-hover:text-indigo-400 transition-colors">
                          {art.title}
                        </p>
                        <p className="text-[10px] text-muted-foreground">{art.sourceName}</p>
                      </div>
                    </Link>
                  ))
                )}
              </div>
            </div>

            {/* CTA Card */}
            <div className="relative rounded-2xl overflow-hidden p-6 text-center space-y-4">
              <div className="absolute inset-0 bg-gradient-to-br from-indigo-600 via-violet-600 to-purple-700" />
              <div className="absolute inset-0 opacity-20"
                style={{ backgroundImage: "radial-gradient(circle at 70% 30%, rgba(255,255,255,0.2) 0%, transparent 60%)" }}
              />
              <div className="relative space-y-4">
                <div className="inline-flex p-3 rounded-2xl bg-white/15 border border-white/25 mx-auto">
                  <BrainCircuit className="h-6 w-6 text-white" />
                </div>
                <div>
                  <h3 className="font-extrabold text-white text-lg leading-tight">
                    Start reading smarter today
                  </h3>
                  <p className="text-white/70 text-xs mt-1 leading-relaxed">
                    Free access to AI summaries, bookmarks & research assistant
                  </p>
                </div>
                <Link
                  href="/auth"
                  className="inline-flex items-center gap-1.5 px-5 py-2.5 rounded-full bg-white text-indigo-700 font-extrabold text-xs hover:bg-white/90 transition-all duration-200 shadow-lg"
                >
                  <Zap className="h-3.5 w-3.5" />
                  Get Started Free
                </Link>
              </div>
            </div>
          </div>
        </div>
      </section>

    </div>
  );
}
